### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by Antoine38660** [machour/git-point-playground#12]
Thanks dude for this repo

**Comment by machour** [comment]
here some updates from me

Repository

I prefer https://github.com/oktokit/octokit.js over https://github.com/oktokit/javascript, because "octokit.js" is what people will refer to it out here, and probably google for it. I definitely prefer https://github.com/oktokit/javascript over https://github.com/oktokit/js for clarity and SEO. "octokit.js" would also follow the conventions of "octokit.rb", "octokit.objc", "octokit.net".


Separate packages

I would setup the repository as a monorepo, which means multiple npm packages will be published from the same repository. There will be one octokit package which will be "all batteries included". But especially for usage in browsers, it makes sense to offer only the subset of functionality as separate packages. Another reason is that some functionality will be useful to other library/app developers. For example, a @octokit/preview-headers would be great to be reusable by others, too. It would only contain the headers which need to be set for the respective URLs, similar to https://github.com/philschatz/octokat.js/blob/master/src/grammar/preview-headers.coffee.

I like PouchDB’s monorepo setup: https://github.com/pouchdb/pouchdb. The overhead is minimal, and all packages are always released with the same version, following the conventions described at https://github.com/boennemann/alle. PouchDB has simple APIs for custom builds: https://pouchdb.com/custom.html

But before going in that direction, I’d setup a way to measure the built file sizes of the library to use in the browser and see if modularisation really has a significant impact or not.

Browser support

Making an octokit.js library run in both Node & browser is pretty straight forward. But with browser support comes the requirements for small bundle sizes. custom builds is one way to address it. Another one is to use browsers native APIs as much as possible and polyfill gaps in Node where a bigger file size is less of a problem.

I would recommend to utilise the new fetch API for requests. There is a drop-in library for node as well as a GitHub’s own polyfill for browsers which do not support fetch. This will significantly reduce the file size of octokit.js. Mikeal’s "spiritual successor to request" is a good showcase of that approach: https://github.com/mikeal/r2. I’ll evaluate r2 as the request library for octokit.js

Testing

I’ve created a separate project to creates fixtures, which automates keeping them up-to-date with GitHub API changes and exports a language agnostic mock-server binary. See my comment at #6 (comment)

What’s next

It would be really helpful if we could finish the move from mikedeboer/node-github soon, or we could simply create an entire new repository octokit/octokit.js as lots of things will change anyway. But having one repository moving forward would make my life much easier maintaining the project 🙏
